[[redirects]]
  from = "/menu"
  to = "https://widgets.dispenseapp.com/:splat"
  status = 200
  force = false
  headers = {dispense-store-id = "075f447fd7e35cd9", dispense-menu-path = "/menu", x-forwarded-host = "jovial-borg-3077ab.netlify.app/" }
