[[redirects]]
  from = "/commcann-rehoboth"
  to = "https://widgets.dispenseapp.com/:splat"
  status = 200
  force = false
  headers = {dispense-store-id = "075f447fd7e35cd9", dispense-menu-path = "/extra", x-forwarded-host = "green-package-testing.netlify.app/" }
